version: "3"

volumes:
  postgres-data:

services:
  avito_service:
    image: kostikan/avito_service:${APP_VERSION}
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - postgres
    env_file:
      - vars.env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres:
    image: kartoza/postgis:13.0
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - vars.env
    ports:
      - "5432:5432"
    restart: on-failure