// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package room_mock is a generated GoMock package.
package room_mock

import (
	roomModel "github.com/Kostikans/avitoTest/internal/app/room/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUsecase is a mock of Usecase interface
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AddRoom mocks base method
func (m *MockUsecase) AddRoom(room roomModel.RoomAdd) (roomModel.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoom", room)
	ret0, _ := ret[0].(roomModel.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRoom indicates an expected call of AddRoom
func (mr *MockUsecaseMockRecorder) AddRoom(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoom", reflect.TypeOf((*MockUsecase)(nil).AddRoom), room)
}

// DeleteRoom mocks base method
func (m *MockUsecase) DeleteRoom(roomID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom
func (mr *MockUsecaseMockRecorder) DeleteRoom(roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockUsecase)(nil).DeleteRoom), roomID)
}

// GetRooms mocks base method
func (m *MockUsecase) GetRooms(order roomModel.RoomOrder) ([]roomModel.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRooms", order)
	ret0, _ := ret[0].([]roomModel.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRooms indicates an expected call of GetRooms
func (mr *MockUsecaseMockRecorder) GetRooms(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockUsecase)(nil).GetRooms), order)
}

// CheckRoomExist mocks base method
func (m *MockUsecase) CheckRoomExist(roomID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRoomExist", roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRoomExist indicates an expected call of CheckRoomExist
func (mr *MockUsecaseMockRecorder) CheckRoomExist(roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRoomExist", reflect.TypeOf((*MockUsecase)(nil).CheckRoomExist), roomID)
}
