// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  responses

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Error ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Error ) UnmarshalJSON([]byte) error { return nil }
func ( Error ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Error ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Error *Error

func ( HttpResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* HttpResponse ) UnmarshalJSON([]byte) error { return nil }
func ( HttpResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* HttpResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_HttpResponse *HttpResponse
