// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package booking_mock is a generated GoMock package.
package booking_mock

import (
	bookingModel "github.com/Kostikans/avitoTest/internal/app/booking/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddBooking mocks base method
func (m *MockRepository) AddBooking(booking bookingModel.BookingAdd) (bookingModel.BookingID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBooking", booking)
	ret0, _ := ret[0].(bookingModel.BookingID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBooking indicates an expected call of AddBooking
func (mr *MockRepositoryMockRecorder) AddBooking(booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBooking", reflect.TypeOf((*MockRepository)(nil).AddBooking), booking)
}

// DeleteBooking mocks base method
func (m *MockRepository) DeleteBooking(bookingID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking
func (mr *MockRepositoryMockRecorder) DeleteBooking(bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockRepository)(nil).DeleteBooking), bookingID)
}

// GetBookings mocks base method
func (m *MockRepository) GetBookings(roomID int) ([]bookingModel.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookings", roomID)
	ret0, _ := ret[0].([]bookingModel.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookings indicates an expected call of GetBookings
func (mr *MockRepositoryMockRecorder) GetBookings(roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookings", reflect.TypeOf((*MockRepository)(nil).GetBookings), roomID)
}

// CheckBookingExist mocks base method
func (m *MockRepository) CheckBookingExist(bookingID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBookingExist", bookingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBookingExist indicates an expected call of CheckBookingExist
func (mr *MockRepositoryMockRecorder) CheckBookingExist(bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBookingExist", reflect.TypeOf((*MockRepository)(nil).CheckBookingExist), bookingID)
}
